### ISSUE TITLE
libtinyWRAP.so fails to load when using multi user mode on Android M

### ISSUE THREAD

**Issue by MassimoMessore** [DoubangoTelecom/imsdroid#566]
**What steps will reproduce the problem?**
- Checkout and build the latest sources of imsdroid 
- Install imsdroid on the primary user account
- Create a new user via "Settings > Users"
- Switch to the new created user account (secondary user)
- Install imsdroid for the secondary user

**What is the expected output? What do you see instead?**
Imsdroid should run fine for both users (like on Android Lollipop). Running Imsdroid on the secondary user causes a crash (see attached log details).

**What version of the product are you using? On what operating system?**
Latest sources of imsdroid running on Android 6.0 on LG Nexus 5 

**Please provide any additional information below.**
Looks like secondary users are not able to access the path "/data/data/org.doubango.imsdroid/lib/". 

**Log details:**

*10-12 15:30:14.599: D/org.doubango.imsdroid.IMSDroid(11349): IMSDroid()
10-12 15:30:14.600: D/org.doubango.ngn.NgnApplication(11349): Build.MODEL=nexus 5
10-12 15:30:14.600: D/org.doubango.ngn.NgnApplication(11349): Build.VERSION.SDK=23
10-12 15:30:14.604: W/linker(11349): /data/app/org.doubango.imsdroid-1/lib/arm/libutils_armv5te.so: unused DT entry: type 0xf arg 0x1438
10-12 15:30:14.609: D/org.doubango.ngn.NgnEngine(11349): CPU_Feature=15
10-12 15:30:14.610: D/org.doubango.ngn.NgnEngine(11349): isCpuNeon()=YES
10-12 15:30:14.613: W/linker(11349): /data/app/org.doubango.imsdroid-1/lib/arm/libtinyWRAP_neon.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
10-12 15:30:14.632: D/org.doubango.ngn.NgnApplication(11349): sGlEsVersion=196608
10-12 15:30:14.644: D/org.doubango.ngn.NgnEngine(11349): Configure AEC[true/100] AEC_TAIL_ADAPT[false] NoiseSuppression[true], Voice activity detection[false]
10-12 15:30:14.645: D/org.doubango.ngn.NgnNativeService(11349): onCreate()
10-12 15:30:14.645: D/org.doubango.imsdroid.NativeService(11349): onCreate()
10-12 15:30:14.646: D/org.doubango.ngn.NgnNativeService(11349): onStart()
10-12 15:30:14.646: D/org.doubango.imsdroid.NativeService(11349): onStart()
10-12 15:30:26.065: D/org.doubango.imsdroid.IMSDroid(11594): IMSDroid()
10-12 15:30:26.066: D/org.doubango.ngn.NgnApplication(11594): Build.MODEL=nexus 5
10-12 15:30:26.066: D/org.doubango.ngn.NgnApplication(11594): Build.VERSION.SDK=23
10-12 15:30:26.072: W/ubango.imsdroid(11594): type=1400 audit(0.0:30719): avc: denied { search } for name="org.doubango.imsdroid" dev="mmcblk0p28" ino=89900 scontext=u:r:untrusted_app:s0:c522,c768 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
10-12 15:30:26.072: W/ubango.imsdroid(11594): type=1400 audit(0.0:30720): avc: denied { search } for name="org.doubango.imsdroid" dev="mmcblk0p28" ino=89900 scontext=u:r:untrusted_app:s0:c522,c768 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
10-12 15:30:26.078: D/AndroidRuntime(11594): Shutting down VM
10-12 15:30:26.078: D/AndroidRuntime(11594): --------- beginning of crash
10-12 15:30:26.079: E/AndroidRuntime(11594): FATAL EXCEPTION: main
10-12 15:30:26.079: E/AndroidRuntime(11594): Process: org.doubango.imsdroid, PID: 11594
10-12 15:30:26.079: E/AndroidRuntime(11594): java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/data/org.doubango.imsdroid/lib/libtinyWRAP.so" not found
10-12 15:30:26.079: E/AndroidRuntime(11594): 	at java.lang.Runtime.load(Runtime.java:332)
10-12 15:30:26.079: E/AndroidRuntime(11594): 	at java.lang.System.load(System.java:1069)
10-12 15:30:26.079: E/AndroidRuntime(11594): 	at org.doubango.ngn.NgnEngine.initialize2(NgnEngine.java:118)
10-12 15:30:26.079: E/AndroidRuntime(11594): 	at org.doubango.ngn.NgnEngine.<clinit>(NgnEngine.java:94)
10-12 15:30:26.079: E/AndroidRuntime(11594): 	at org.doubango.imsdroid.Main.<init>(Main.java:69)
10-12 15:30:26.079: E/AndroidRuntime(11594): 	at java.lang.Class.newInstance(Native Method)
10-12 15:30:26.079: E/AndroidRuntime(11594): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
10-12 15:30:26.079: E/AndroidRuntime(11594): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
10-12 15:30:26.079: E/AndroidRuntime(11594): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
10-12 15:30:26.079: E/AndroidRuntime(11594): 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
10-12 15:30:26.079: E/AndroidRuntime(11594): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
10-12 15:30:26.079: E/AndroidRuntime(11594): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-12 15:30:26.079: E/AndroidRuntime(11594): 	at android.os.Looper.loop(Looper.java:148)
10-12 15:30:26.079: E/AndroidRuntime(11594): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
10-12 15:30:26.079: E/AndroidRuntime(11594): 	at java.lang.reflect.Method.invoke(Native Method)
10-12 15:30:26.079: E/AndroidRuntime(11594): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-12 15:30:26.079: E/AndroidRuntime(11594): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-12 15:30:41.558: D/org.doubango.imsdroid.IMSDroid(12371): IMSDroid()
10-12 15:30:41.552: W/ubango.imsdroid(12371): type=1400 audit(0.0:30721): avc: denied { search } for name="org.doubango.imsdroid" dev="mmcblk0p28" ino=89900 scontext=u:r:untrusted_app:s0:c522,c768 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
10-12 15:30:41.562: W/ubango.imsdroid(12371): type=1400 audit(0.0:30722): avc: denied { search } for name="org.doubango.imsdroid" dev="mmcblk0p28" ino=89900 scontext=u:r:untrusted_app:s0:c522,c768 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
10-12 15:30:41.559: D/org.doubango.ngn.NgnApplication(12371): Build.MODEL=nexus 5
10-12 15:30:41.559: D/org.doubango.ngn.NgnApplication(12371): Build.VERSION.SDK=23
10-12 15:30:41.566: D/AndroidRuntime(12371): Shutting down VM
10-12 15:30:41.567: E/AndroidRuntime(12371): FATAL EXCEPTION: main
10-12 15:30:41.567: E/AndroidRuntime(12371): Process: org.doubango.imsdroid, PID: 12371
10-12 15:30:41.567: E/AndroidRuntime(12371): java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/data/org.doubango.imsdroid/lib/libtinyWRAP.so" not found
10-12 15:30:41.567: E/AndroidRuntime(12371): 	at java.lang.Runtime.load(Runtime.java:332)
10-12 15:30:41.567: E/AndroidRuntime(12371): 	at java.lang.System.load(System.java:1069)
10-12 15:30:41.567: E/AndroidRuntime(12371): 	at org.doubango.ngn.NgnEngine.initialize2(NgnEngine.java:118)
10-12 15:30:41.567: E/AndroidRuntime(12371): 	at org.doubango.ngn.NgnEngine.<clinit>(NgnEngine.java:94)
10-12 15:30:41.567: E/AndroidRuntime(12371): 	at org.doubango.imsdroid.Main.<init>(Main.java:69)
10-12 15:30:41.567: E/AndroidRuntime(12371): 	at java.lang.Class.newInstance(Native Method)
10-12 15:30:41.567: E/AndroidRuntime(12371): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
10-12 15:30:41.567: E/AndroidRuntime(12371): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
10-12 15:30:41.567: E/AndroidRuntime(12371): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
10-12 15:30:41.567: E/AndroidRuntime(12371): 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
10-12 15:30:41.567: E/AndroidRuntime(12371): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
10-12 15:30:41.567: E/AndroidRuntime(12371): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-12 15:30:41.567: E/AndroidRuntime(12371): 	at android.os.Looper.loop(Looper.java:148)
10-12 15:30:41.567: E/AndroidRuntime(12371): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
10-12 15:30:41.567: E/AndroidRuntime(12371): 	at java.lang.reflect.Method.invoke(Native Method)
10-12 15:30:41.567: E/AndroidRuntime(12371): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-12 15:30:41.567: E/AndroidRuntime(12371): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-12 15:30:46.415: I/Process(12371): Sending signal. PID: 12371 SIG: 9*

**Comment by DoubangoTelecom** [comment]
Fixed

**Comment by yash2710** [comment]
As of today, the error is prevailing.
