### ISSUE TITLE
OpenSSL contain security vulnerabilities.

### ISSUE THREAD

**Issue by eugeneGoodwin** [DoubangoTelecom/imsdroid#584]
This information is intended for developers of apps statically linking against a version of OpenSSL that precedes 1.02f/1.01r.  These versions contain security vulnerabilities.  

Please migrate your app(s) to OpenSSL 1.02f/1.01r or higher as soon as possible and increment the version number of the upgraded APK. Beginning July 11, 2016, Google Play will block publishing of any new apps or updates that use older versions of OpenSSL. Your published app version will remain unaffected, however any updates to the app will be blocked unless they address this vulnerability.

is there anyway to fix this? Thanks.

**Comment by bdcs001** [comment]
I am also facing same problems.

**Comment by DoubangoTelecom** [comment]
https://github.com/DoubangoTelecom/imsdroid/commit/7454f8db01423e90d59823664ec109a5f9a3afc4
