### ISSUE TITLE
OpenSSL vulnerabilities Issue

### ISSUE THREAD

**Issue by akmaljaved204** [DoubangoTelecom/imsdroid#587]
Hi 
    I am using Doubango Library to Develop Android Application.  I have upload on google play store the Application has rejected due to OpenSSL vulnerabilities. Play store error is below 

Security alert
Your app is using a version of OpenSSL containing a security vulnerability. Please see this Google Help Center article for details, including the deadline for fixing the vulnerability. 

Please migrate your app(s) to OpenSSL 1.02f/1.01r or higher as soon as possible and increment the version number of the upgraded APK. Beginning July 11, 2016, Google Play will block publishing of any new apps or updates that use older versions of OpenSSL. Your published app version will remain unaffected, however any updates to the app will be blocked unless they address this vulnerability.

Please help me at this issue 
Thanks in advance

**Comment by gang018** [comment]
it's a copy
https://github.com/DoubangoTelecom/imsdroid/issues/578

**Comment by akmaljaved204** [comment]
Thank you very much for replay me. 
 I have pull master and build again the Google play issue fixed.

Thank you
