### ISSUE TITLE
NgnApplication is null

### ISSUE THREAD

**Issue by MatheusSuffi** [DoubangoTelecom/imsdroid#590]
hi.

Every time i try to call the function getInstance() from NgnApplication, it returns null.

Complete error message:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference

Thank you

**Comment by gang018** [comment]
Hi
Did you extend your Application class from NgnApplication ?

**Comment by MatheusSuffi** [comment]
just found the sollution.
i put this line in my AndroidManifest.xml:
android:name="org.doubango.ngn.NgnApplication"
