### ISSUE TITLE
how to rebuild to solve text relocation issue

### ISSUE THREAD

**Issue by zaferaydn** [DoubangoTelecom/imsdroid#600]
As mentioned in some other threads, I have also text relocation error with .so libraries in Android 6 and 7:
`java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.myapp/lib/x86/libtinyWRAP.so: has text relocations`

I saw it can be solved with rebuilding c++ source code of `libtinyWRAP.so` without `ffmpeg `and `h264`. But how can i rebuild the source code of these libraries? I checked `doubango `C project also, but i could not find any instruction for that.

Can someone direct us to a manual that we can learn how to solve this issue? or is it already planned to fix this?

**Comment by DoubangoTelecom** [comment]
https://github.com/DoubangoTelecom/doubango/commit/e58bfcddf01b23eb3fa66063ffbb7e3765943d79

**Comment by nighthunter3173** [comment]
in android_build.sh of doubango, you can modify export variables and set value of ffmepg and h264 to "no".
