### ISSUE TITLE
x64 support

### ISSUE THREAD

**Issue by behelit** [DoubangoTelecom/imsdroid#609]
The play store will require 64 bit support for native code by August 2019 (https://www.androidpolice.com/2017/12/19/play-store-require-new-updated-apps-target-recent-api-levels-distribute-native-apps-64-bit-support/)

Will this be possible?

**Comment by behelit** [comment]
This deadline is approaching soon. How can we obtain x64 libs?

**Comment by DoubangoTelecom** [comment]
Will be updated before May 1st

Le 4/3/2019 à 7:36 AM, behelit a écrit :

**Comment by DoubangoTelecom** [comment]
Latest release adds support for x86_64 and arm64
