### ISSUE TITLE
configuration and setup guide for Android Studio?

### ISSUE THREAD

**Issue by omerasif57** [DoubangoTelecom/imsdroid#614]
Setup guide provided for android-ngn-stack is for Eclipse. 
Any pointer to setup for android studio? 
Please Advise.

**Comment by FarhanAhmad** [comment]
You can import it in Android Studio easily. Open Android Studio->Open an existing Android Studio project. Navigate to IMSDroid. and It will load the project (since it has the gradle files). If you have any specific problem related to importing, feel free to explain.

**Comment by omerasif57** [comment]
@FarhanAhmad Thanks for the support. I have build the project. Though, I faced few difficulties. If I get time, I will write about the necessary steps (for beginners, I assume). Good Day!

**Comment by nighthunter3173** [comment]
Hello! I met many worries, do you have a github repository with an example of the use of this library on android studio. I'm trying to add this library to an existing project to communicate with an asterisk server

**Comment by wjswlgus123** [comment]
could you please share the android studio build configuration? for repository?

**Comment by omerasif57** [comment]
> could you please share the android studio build configuration? for repository?

This is updated [android-ngn-stack manifest](https://pastebin.com/2Ac5V6vz)
This is updated [android-ngn-stack gradle.build](https://pastebin.com/eysQMMT7)
This is updated [imsdroid manifest](https://pastebin.com/da7DmKc2)
This is updated [imsdroid gradle.build](https://pastebin.com/K1V0EtJx)
update build tools accordingly, if needed. I have abandoned this specific project a long time ago without any advance knowledge in hand. 
Btw, It is very easy to build if you don't give up too early. 
I have tested this config on a device with `Android 5.1(lollipop)` only.
And if you encounter any `app:processDebugResources` error just remove `@` symbol in `/imsdroid/res/values/styles.xml`. After that, I think you are good to go with this config. 

> Hello! I met many worries, do you have a github repository with an example of the use of this library on android studio. I'm trying to add this library to an existing project to communicate with an asterisk server

Don't worry, It is easy to understand the code if this is not your first android project. 
Here is what one can do to get started:
When you done with building the repo successfully, Run the imsdroid app (inside `imsdroid/` ) on android device first. imsdroid app has all the features to interact with an ivr server. Then you can go to imsdroid code(with or withour debug mode) and see how things are implemented. (So that you can replicate within your new client app).
